import type { Prescription } from '../../../core/api/types';
import { formatDate } from '../../../core/utils/format';

function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]!);
}

/**
 * Opens a standalone, self-styled window with the prescription laid out for printing,
 * and triggers the browser's print dialog — "Save as PDF" there is the download path.
 * A real PDF export would need a client library (jsPDF/html2canvas); this avoids adding
 * one for a single printout. The new window has no access to the app's own CSS, so the
 * markup is self-contained rather than reusing shared components.
 */
export function openPrescriptionPrintWindow(
  prescription: Prescription,
  hospitalName: string | null,
): boolean {
  const printWindow = window.open('', '_blank', 'noopener,width=720,height=900');
  if (!printWindow) return false;

  const medicineRows = prescription.medicines
    .map(
      (item) => `
        <tr>
          <td>${escapeHtml(item.medicationName)}</td>
          <td>${escapeHtml(item.dosage)}</td>
          <td>${escapeHtml(item.frequency)}</td>
          <td>${item.durationDays ? `${item.durationDays} days` : '—'}</td>
          <td>${item.instructions ? escapeHtml(item.instructions) : '—'}</td>
        </tr>`,
    )
    .join('');

  printWindow.document.write(`<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<title>Prescription — ${escapeHtml(prescription.patientName)}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; color: #1a1a1a; padding: 32px; max-width: 640px; margin: 0 auto; }
  .header { display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 1px solid #333; padding-bottom: 12px; margin-bottom: 16px; }
  .header h1 { font-size: 18px; margin: 0; }
  .header .meta { text-align: right; font-size: 12px; color: #555; }
  .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin-bottom: 16px; }
  .label { font-size: 11px; color: #777; margin: 0; }
  .value { font-size: 14px; font-weight: 600; margin: 2px 0 0; }
  .section-label { font-size: 11px; color: #777; margin: 0 0 6px; }
  table { width: 100%; border-collapse: collapse; font-size: 12.5px; margin-bottom: 16px; }
  th, td { text-align: left; padding: 6px 4px; border-bottom: 1px solid #e0e0e0; }
  th { color: #777; font-weight: 600; }
  .footer { display: flex; justify-content: space-between; align-items: center; border-top: 1px solid #333; padding-top: 14px; font-size: 12px; }
  .signed { background: #e1f2e8; color: #1d7a45; padding: 3px 10px; border-radius: 4px; }
  @media print { body { padding: 0; } }
</style>
</head>
<body>
  <div class="header">
    <div>
      <h1>${escapeHtml(hospitalName ?? 'MedFlow Hospital')}</h1>
    </div>
    <div class="meta">
      <p style="margin:0">Date</p>
      <p style="margin:2px 0 0">${formatDate(prescription.createdAt)}</p>
    </div>
  </div>
  <div class="grid">
    <div>
      <p class="label">Patient</p>
      <p class="value">${escapeHtml(prescription.patientName)}</p>
    </div>
    <div>
      <p class="label">Doctor</p>
      <p class="value">${escapeHtml(prescription.doctorName)}</p>
    </div>
  </div>
  <div style="margin-bottom:16px">
    <p class="section-label">Diagnosis</p>
    <p style="margin:0;font-size:13px">${prescription.diagnosis ? escapeHtml(prescription.diagnosis) : '—'}</p>
  </div>
  <div>
    <p class="section-label">Rx</p>
    <table>
      <thead><tr><th>Medicine</th><th>Dosage</th><th>Frequency</th><th>Duration</th><th>Instructions</th></tr></thead>
      <tbody>${medicineRows}</tbody>
    </table>
  </div>
  <div class="footer">
    <span>${prescription.status === 'CANCELLED' ? '<strong style="color:#b42318">CANCELLED</strong>' : prescription.digitallySigned ? '<span class="signed">Digitally signed</span>' : 'Draft — not signed'}</span>
    <span>Generated by MedFlow AI</span>
  </div>
</body>
</html>`);
  printWindow.document.close();
  printWindow.focus();
  printWindow.onload = () => printWindow.print();
  return true;
}
