import { jsPDF } from 'jspdf';
import { autoTable } from 'jspdf-autotable';
import type { Prescription } from '../../../core/api/types';
import { formatDate } from '../../../core/utils/format';

function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]!);
}

/** A standalone, self-styled document — has no access to the app's own CSS. */
function buildPrescriptionHtml(prescription: Prescription, hospitalName: string | null): string {
  const medicineRows = prescription.medicines
    .map(
      (item) => `
        <tr>
          <td>${escapeHtml(item.medicationName)}</td>
          <td>${escapeHtml(item.dosage)}</td>
          <td>${escapeHtml(item.frequency)}</td>
          <td>${item.durationDays ? `${item.durationDays} days` : '—'}</td>
          <td>${item.instructions ? escapeHtml(item.instructions) : '—'}</td>
        </tr>`,
    )
    .join('');

  return `<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<title>Prescription — ${escapeHtml(prescription.patientName)}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; color: #1a1a1a; padding: 32px; max-width: 640px; margin: 0 auto; }
  .header { display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 1px solid #333; padding-bottom: 12px; margin-bottom: 16px; }
  .header h1 { font-size: 18px; margin: 0; }
  .header .meta { text-align: right; font-size: 12px; color: #555; }
  .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin-bottom: 16px; }
  .label { font-size: 11px; color: #777; margin: 0; }
  .value { font-size: 14px; font-weight: 600; margin: 2px 0 0; }
  .section-label { font-size: 11px; color: #777; margin: 0 0 6px; }
  table { width: 100%; border-collapse: collapse; font-size: 12.5px; margin-bottom: 16px; }
  th, td { text-align: left; padding: 6px 4px; border-bottom: 1px solid #e0e0e0; }
  th { color: #777; font-weight: 600; }
  .footer { display: flex; justify-content: space-between; align-items: center; border-top: 1px solid #333; padding-top: 14px; font-size: 12px; }
  .signed { background: #e1f2e8; color: #1d7a45; padding: 3px 10px; border-radius: 4px; }
  @media print { body { padding: 0; } }
</style>
</head>
<body>
  <div class="header">
    <div>
      <h1>${escapeHtml(hospitalName ?? 'MedFlow Hospital')}</h1>
    </div>
    <div class="meta">
      <p style="margin:0">Date</p>
      <p style="margin:2px 0 0">${formatDate(prescription.createdAt)}</p>
    </div>
  </div>
  <div class="grid">
    <div>
      <p class="label">Patient</p>
      <p class="value">${escapeHtml(prescription.patientName)}</p>
    </div>
    <div>
      <p class="label">Doctor</p>
      <p class="value">${escapeHtml(prescription.doctorName)}</p>
    </div>
  </div>
  <div style="margin-bottom:16px">
    <p class="section-label">Diagnosis</p>
    <p style="margin:0;font-size:13px">${prescription.diagnosis ? escapeHtml(prescription.diagnosis) : '—'}</p>
  </div>
  <div>
    <p class="section-label">Rx</p>
    <table>
      <thead><tr><th>Medicine</th><th>Dosage</th><th>Frequency</th><th>Duration</th><th>Instructions</th></tr></thead>
      <tbody>${medicineRows}</tbody>
    </table>
  </div>
  <div class="footer">
    <span>${prescription.status === 'CANCELLED' ? '<strong style="color:#b42318">CANCELLED</strong>' : prescription.digitallySigned ? '<span class="signed">Digitally signed</span>' : 'Draft — not signed'}</span>
    <span>Generated by MedFlow AI</span>
  </div>
</body>
</html>`;
}

/**
 * Prints via a hidden iframe rather than `window.open` — a new window/tab is subject to
 * the browser's popup blocker even on a genuine click (confirmed live: it was blocked),
 * while an iframe appended to the current page is not a popup at all, so this can't be
 * blocked the same way.
 */
export function printPrescription(prescription: Prescription, hospitalName: string | null) {
  const iframe = document.createElement('iframe');
  iframe.style.position = 'fixed';
  iframe.style.right = '0';
  iframe.style.bottom = '0';
  iframe.style.width = '0';
  iframe.style.height = '0';
  iframe.style.border = '0';
  iframe.setAttribute('aria-hidden', 'true');

  const cleanup = () => {
    if (iframe.parentNode) document.body.removeChild(iframe);
  };

  iframe.onload = () => {
    const win = iframe.contentWindow;
    if (!win) {
      cleanup();
      return;
    }
    win.focus();
    win.print();
    // Some browsers fire this after the print dialog closes; others never do, so this
    // is a courtesy cleanup, not something either action depends on.
    win.onafterprint = cleanup;
    setTimeout(cleanup, 10_000);
  };

  document.body.appendChild(iframe);
  iframe.srcdoc = buildPrescriptionHtml(prescription, hospitalName);
}

const PAGE_WIDTH = 210;
const MARGIN = 15;
const RIGHT_EDGE = PAGE_WIDTH - MARGIN;

function buildPrescriptionPdf(prescription: Prescription, hospitalName: string | null): jsPDF {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  let y = 20;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(20);
  doc.text(hospitalName ?? 'MedFlow Hospital', MARGIN, y);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(formatDate(prescription.createdAt), RIGHT_EDGE, y, { align: 'right' });

  y += 4;
  doc.setDrawColor(210);
  doc.line(MARGIN, y, RIGHT_EDGE, y);
  y += 10;

  doc.setFontSize(9);
  doc.setTextColor(130);
  doc.text('Patient', MARGIN, y);
  doc.text('Doctor', 110, y);
  y += 6;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(20);
  doc.text(prescription.patientName, MARGIN, y);
  doc.text(prescription.doctorName, 110, y);
  y += 10;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(130);
  doc.text('Diagnosis', MARGIN, y);
  y += 6;
  doc.setFontSize(11);
  doc.setTextColor(20);
  const diagnosisLines = doc.splitTextToSize(prescription.diagnosis || '—', RIGHT_EDGE - MARGIN);
  doc.text(diagnosisLines, MARGIN, y);
  y += diagnosisLines.length * 5 + 8;

  doc.setFontSize(9);
  doc.setTextColor(130);
  doc.text('Rx', MARGIN, y);
  y += 3;

  autoTable(doc, {
    startY: y,
    margin: { left: MARGIN, right: MARGIN },
    head: [['Medicine', 'Dosage', 'Frequency', 'Duration', 'Instructions']],
    body: prescription.medicines.map((item) => [
      item.medicationName,
      item.dosage,
      item.frequency,
      item.durationDays ? `${item.durationDays} days` : '—',
      item.instructions || '—',
    ]),
    styles: { fontSize: 9, cellPadding: 2.5, textColor: 20 },
    headStyles: { fillColor: [240, 240, 238], textColor: 90, fontStyle: 'bold' },
  });

  // jspdf-autotable attaches this at runtime (not in jsPDF's own type definitions).
  const finalY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 10;
  doc.setDrawColor(210);
  doc.line(MARGIN, finalY, RIGHT_EDGE, finalY);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  if (prescription.status === 'CANCELLED') {
    doc.setTextColor(180, 40, 30);
    doc.text('CANCELLED', MARGIN, finalY + 7);
  } else if (prescription.digitallySigned) {
    doc.setTextColor(30, 120, 70);
    doc.text('Digitally signed', MARGIN, finalY + 7);
  } else {
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(120);
    doc.text('Draft — not signed', MARGIN, finalY + 7);
  }

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(150);
  doc.text('Generated by MedFlow AI', RIGHT_EDGE, finalY + 7, { align: 'right' });

  return doc;
}

/**
 * Builds and saves a real PDF client-side (jsPDF + jspdf-autotable). `doc.save()`
 * triggers the same Blob-download mechanism as a manual anchor click — not a popup, so
 * it can't be caught by a popup blocker the way `window.open` was.
 */
export function downloadPrescription(prescription: Prescription, hospitalName: string | null) {
  const doc = buildPrescriptionPdf(prescription, hospitalName);
  doc.save(`prescription-${prescription.id}.pdf`);
}
